/*
 * PanelBusquedas.java
 *
 * Created on 19 de diciembre de 2007, 20:21
 */

package com.codeko.apps.campanilla.ignotus;

/**
 *
 * @author  campanilla
 */
public class PanelBusquedas extends javax.swing.JPanel {
    
    /** Creates new form PanelBusquedas */
    public PanelBusquedas() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelBusquedaSimple1 = new com.codeko.apps.campanilla.ignotus.PanelBusquedaSimple();
        panelTablaLibros1 = new com.codeko.apps.campanilla.ignotus.PanelTablaLibros();

        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panelBusquedaSimple1.setName("panelBusquedaSimple1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.campanilla.ignotus.IgnotusApp.class).getContext().getResourceMap(PanelBusquedas.class);
        jTabbedPane1.addTab(resourceMap.getString("panelBusquedaSimple1.TabConstraints.tabTitle"), panelBusquedaSimple1); // NOI18N

        panelTablaLibros1.setName("panelTablaLibros1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelTablaLibros1.TabConstraints.tabTitle"), panelTablaLibros1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.codeko.apps.campanilla.ignotus.PanelBusquedaSimple panelBusquedaSimple1;
    private com.codeko.apps.campanilla.ignotus.PanelTablaLibros panelTablaLibros1;
    // End of variables declaration//GEN-END:variables
    
}
