/*
 * PanelDedicatoria.java
 *
 * Created on 31 de diciembre de 2007, 18:36
 */

package com.codeko.apps.campanilla.ignotus;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;

/**
 *
 * @author  campanilla
 */
public class PanelDedicatoria extends javax.swing.JPanel {
    
    /** Creates new form PanelDedicatoria */
    public PanelDedicatoria() {
        initComponents();
        taDedicatoria.setText("<p>Para mi hermano chiquitito con cariño de TheLittleMoleWoman y TheSligthyRadioactiveMan</p></p>");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollDedicatoria = new javax.swing.JScrollPane();
        taDedicatoria = new javax.swing.JTextPane();

        setName("Form"); // NOI18N

        scrollDedicatoria.setName("scrollDedicatoria"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.campanilla.ignotus.IgnotusApp.class).getContext().getResourceMap(PanelDedicatoria.class);
        taDedicatoria.setContentType(resourceMap.getString("taDedicatoria.contentType")); // NOI18N
        taDedicatoria.setName("taDedicatoria"); // NOI18N
        scrollDedicatoria.setViewportView(taDedicatoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollDedicatoria, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollDedicatoria, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollDedicatoria;
    private javax.swing.JTextPane taDedicatoria;
    // End of variables declaration//GEN-END:variables
    
}
